//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseAppDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        public string Name { get; set; }
        public string Heads { get; set; }
        public int StudentCount { get; set; }
        public decimal Salary { get; set; }
        public bool IsCool { get; set; }
    }
}
